version: '2.3'

services:
    python:
        build:
            context: .
            dockerfile: docker/Dockerfile
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - .:/usr/src
            - /mnt/D/Data/animefacedataset:/usr/src/data
        working_dir: /usr/src
        tty: true